# Generated by Django 5.2.6 on 2025-11-04 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, unique=True)),
                ('board', models.CharField(default='_________', max_length=9)),
                ('active_player', models.IntegerField(default=1)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('WON_P1', 'Won by Player 1'), ('WON_P2', 'Won by Player 2'), ('TIE', 'Tie')], default='ACTIVE', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
