# Generated by Django 5.2.6 on 2025-11-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
